title: "Cartório"
description: "Registro Civil, Notas e Protesto"
baseurl: "/cartorio-site"
url: "https://crednom.github.io"
markdown: kramdown
permalink: pretty

collections:
  setores:
    output: true
    permalink: /setores/:name/
  servicos:
    output: true
    permalink: /servicos/:name/
  artigos:
    output: true
    permalink: /artigos/:name/

defaults:
  - scope:
      path: ""
      type: "servicos"
    values:
      layout: "servico"
  - scope:
      path: ""
      type: "setores"
    values:
      layout: "setor"
  - scope:
      path: ""
      type: "artigos"
    values:
      layout: "artigo"

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
